spring:
  config:
    activate:
      on-profiles: local
  application:
    name: todo-list
    description: API todo-list
server:
  address: 0.0.0.0
  port: 8080
  error:
    whitelabel:
      enabled: false
  security:
    basic:
      enabled: false
management:
  server:
    port: 9090
    security:
      enabled: false
  endpoint:
    health:
      show-details: ALWAYS
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics

---
spring:
  config:
    on-profiles: local
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false
  datasource:
    url: jdbc:h2:mem:todolistdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasourcer-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

