CREATE TABLE TB_USER (
    ID_USER INT NOT NULL AUTO_INCREMENT,
    CLIENT_ID VARCHAR(50) NOT NULL,
    CLIENT_SECRET VARCHAR(50) NOT NULL,
    ADMIN CHAR(1) NOT NULL,
    PRIMARY KEY (ID_USER)
);

CREATE TABLE TB_STATUS (
    ID_STATUS INT NOT NULL AUTO_INCREMENT,
    NAME_STATUS VARCHAR(10),
    DT_INSERT DATETIME NOT NULL,
    DT_UPDATE DATETIME,
    PRIMARY KEY (ID_STATUS)
);

CREATE TABLE TB_TASK (
    ID_TASK INT NOT NULL AUTO_INCREMENT,
    ID_USER INT NOT NULL,
    ID_STATUS INT NOT NULL,
    RESUME VARCHAR(100),
    DESCRIPTION VARCHAR(100),
    DT_INSERT DATETIME NOT NULL,
    DT_UPDATE DATETIME,
    PRIMARY KEY (ID_TASK),
    FOREIGN KEY (ID_USER) REFERENCES TB_USER(ID_USER),
    FOREIGN KEY (ID_STATUS) REFERENCES TB_STATUS(ID_STATUS)
);


